### ISSUE TITLE
"server2.js" you mean server.js right ?

### ISSUE THREAD

**Issue by atoulous** [tudorconstantin/knests#626]
https://github.com/tudorconstantin/knests/blob/64b0536ce4a678379f220aea61950e0a4044027d/client/package.json#L6

**Comment by tudorconstantin** [comment]
Yes, that's right. There was a `server2.js` file while migrating to the newer next.js version and I forgot to remove its reference from package.json when I promoted it to server.js

I pushed a fix for this. 

Thanks for noticing it!
